### ISSUE TITLE
新增政黨比例圓餅圖 pie chart

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/dataly#11]
建立一個資料視覺化：政黨比例圓餅圖 pie chart
也透過這單了解怎麼透過 Chart.js 引入一個新的資料視覺化

#### TODO
- [x] add party color code in App\Utils\Helper.php
- [ ] 在 DashboardController 計算圓餅圖所需的資料
- [ ] 建立所需的 `Chart.js` 架構
- [ ] 在 dashboard.blade.php 傳遞資料給 `chart-pie.js` 產生圖片
