### ISSUE TITLE
將 law-diff 的功能搬到 dataly

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/dataly#14]
[law-diff Github](https://github.com/openfunltd/law-diff)

#### TODO
- [x] 安裝 js package [text-diff](https://www.npmjs.com/package/text-diff)
- [x] 將 js script 對接進 php 程式碼裡頭
- [x] 前端 - 關聯議案 table
- [x] 前端 - 條文索引
- [x] 前端 - 各條文法律對照
- [x] js - 根據勾選的關聯議案隱藏/顯示條文比較

**Comment by typingmonk** [comment]
Done. Issue closed
